spring:
  datasource:
    url:  jdbc:h2:./vote_database;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /vote_database
      settings:
        web-allow-others: true
